apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: route-get-bank-logo
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-bank-logo
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_bank_logo
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_bank_logo
